name: ecommerce_de_project
version: "1.0"
config-version: 2

profile: ecommerce_de_project

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# -------------------------------------------------
# Variables
# -------------------------------------------------
vars:
  target_date: "20240123"

# -------------------------------------------------
# Model configuration
# -------------------------------------------------
models:
  ecommerce_de_project:

    staging:
      +materialized: view
      +schema: staging

    raw_vault:
      +materialized: incremental
      +schema: raw_vault

    business_vault:
      +materialized: table
      +schema: business_vault

    marts:
      +materialized: table
      +schema: mart

# -------------------------------------------------
# Hooks
# -------------------------------------------------
on-run-end:
  - "{{ log_dbt_results(results) }}"
  - "{{ log_test_results(results) }}"

# -------------------------------------------------
# Flags
# -------------------------------------------------
flags:
  indirect_selection: cautious