ecommerce_de_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin@admin.com
      password: admin
      port: 5432
      dbname: ecommerce
      schema: staging
      threads: 4